version: "3.9"

services:
  wiremock:
    image: wiremock/wiremock:2.35.0
    container_name: wiremock
    ports:
      - "8089:8080"
    volumes:
      - ./mappings:/home/wiremock/mappings
    command: ["--verbose"]