apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: kafka-headless
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:8.1.1
          ports:
            - containerPort: 9092
              name: kafka
            - containerPort: 9093
              name: controller
          env:
            # ==========================
            # Node identity
            # ==========================

            - name: KAFKA_NODE_ID
              value: "1"
            # Controller + Broker
            - name: KAFKA_PROCESS_ROLES
              value: "broker,controller"
            # KRaft quorum

            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@kafka-0.kafka-headless.default.svc.cluster.local:9093"

            - name: KAFKA_LISTENERS

              value: >
                SASL_PLAINTEXT://:9092,
                CONTROLLER://:9093

            - name: KAFKA_ADVERTISED_LISTENERS

              value: >
                SASL_PLAINTEXT://kafka-0.kafka-headless.default.svc.cluster.local:9092

            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP

              value: >
                CONTROLLER:PLAINTEXT,
                SASL_PLAINTEXT:SASL_PLAINTEXT

            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: CONTROLLER
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: SASL_PLAINTEXT
            - name: KAFKA_SASL_ENABLED_MECHANISMS
              value: PLAIN
            - name: KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL
              value: PLAIN
            - name: KAFKA_SUPER_USERS
              value: User:admin

            - name: KAFKA_OPTS
              value: >
                -Djava.security.auth.login.config=/etc/kafka/jaas/kafka_server_jaas.conf

          volumeMounts:
            - name: kafka-data
              mountPath: /var/lib/kafka/data

            - name: kafka-jaas
              mountPath: /etc/kafka/jaas

      volumes:
        - name: kafka-jaas

          configMap:
            name: kafka-jaas

  volumeClaimTemplates:
    - metadata:
        name: kafka-data

      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi